# Sveltia CMS configuration

# This is where we configure the CMS repo and its collections and fields
# Sveltia CMS generally follows the Decap CMS configuration spec
# Decap CMS docs: https://decapcms.org/docs/intro/
# Sveltia CMS docs: https://github.com/sveltia/sveltia-cms#features

# Enter your GitHub repo path and branch (defaults to master)
backend:
  name: github
  repo: paddymccallan/eleventy-sveltia-cms-starter
  branch: master
  automatic_deployments: false

# The folder used to store uploaded images
media_folder: "assets/img"

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - name: 'products'
    label: 'Product'
    label_singular: 'Product'
    folder: 'content/products'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'projects/{{slug}}'
    fields:
      - {
          label: 'Product Category',
          name: 'category',
          widget: 'select',
          options: [
            { label: 'Low Back Monks Benches', value: 'low-back-monks-benches' },
            { label: 'Tall Monks Benches', value: 'tall-monks-benches' },
            { label: 'Tyrone Style Monks Bench', value: 'tyrone-style-monks-bench' },
            { label: 'Plain Style Coat Rack', value: 'plain-style-coat-rack' },
            { label: 'Basket Coat Racks', value: 'basket-coat-racks' },
            { label: 'Radiator Covers', value: 'radiator-covers' },
            { label: 'Standard Toy Box', value: 'standard-toy-box' },
            { label: 'Large Toy Box', value: 'large-toy-box' },
            { label: 'Victorian Toy Box', value: 'victorian-toy-box' },
            { label: 'Personalised Dog Beds', value: 'personalised-dog-beds' },
            { label: 'Victorian Style Monks Benches', value: 'victorian-style-monks-benches' },
            { label: 'Dog beds / Dog racks', value: 'victorian-style-monks-benches' },
            { label: 'More shoe storage', value: 'shoe-storage' },
          ],
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
      - {
          label: 'Gallery',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.image}}',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
  - name: 'home-products'
    label: 'Home Page Items'
    label_singular: 'Home Page Item'
    folder: 'content/home-products'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Order', name: 'order', widget: 'number', required: true }
      - {
          label: 'Title',
          name: 'title',
          widget: 'string',
          required: true
        }
      - {
          label: 'Cover Image',
          name: 'cover',
          widget: 'image',
          required: true
        }
      - {
          label: 'Category',
          name: 'category',
          widget: 'select',
          options: [
            { label: 'Low Back Monks Benches', value: 'low-back-monks-benches' },
            { label: 'Tall Monks Benches', value: 'tall-monks-benches' },
            { label: 'Tyrone Style Monks Bench', value: 'tyrone-style-monks-bench' },
            { label: 'Plain Style Coat Rack', value: 'plain-style-coat-rack' },
            { label: 'Basket Coat Racks', value: 'basket-coat-racks' },
            { label: 'Radiator Covers', value: 'radiator-covers' },
            { label: 'Standard Toy Box', value: 'standard-toy-box' },
            { label: 'Large Toy Box', value: 'large-toy-box' },
            { label: 'Victorian Toy Box', value: 'victorian-toy-box' },
            { label: 'Victorian Style Monks Benches', value: 'victorian-style-monks-benches' },
            { label: 'Dog beds / Dog racks', value: 'victorian-style-monks-benches' },
            { label: 'More shoe storage', value: 'shoe-storage' },
          ],
          required: true
        }
      - {
          label: 'Tag',
          name: 'tag',
          widget: 'string',
          required: false
        }

